app.jwt.secret = 766c664055363d6e783a4a4b732f316c22797b3f70545e426a3664363c
spring.application.name=backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databasename=projet-eni;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=@|w17935Ph

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

logging.level.sql=debug
logging.level.org.springframework.security=TRACE